In [ ]:
import array
import numpy as np

arr = np.array([1,2,3], ndmin=3)
print(arr)
print(np.shape(arr))

print("")

arr2 = np.array([1,2,3,4,5,6,7])
print(arr2[1:5:2])                    #Slices are a view of the array, changing them changes the main array aswell

print("")

arr3 = np.array([[[1,2,3],[1,2,3],[1,2,3]],
                  [[1,2,3],[1,2,3],[1,2,3]],
                  [[1,2,3],[1,2,3],[1,2,3],]])
print(np.shape(arr3))
print(arr3.dtype)
arr4 = arr3.view()
arr5 = arr3.copy()
arr3[0,0,0] = 100
print("array4 gets changed since it is a shallow copy")
print(arr4[0,0,0])
print("array5 is a deep copy so does not")
print(arr5[0,0,0])

print("")

arr6 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr7 = arr6.reshape(3,4)    #shallow copy, 3 by 4 2d instead of ld
arr6[0] = 9                   

#iterate over any dimension
for x in np.nditer(arr7):
    print(x)


[[[1 2 3]]]
(1, 1, 3)

[2 4]

(3, 3, 3)
int64
array4 gets changed since it is a shallow copy
100
array5 is a deep copy so does not
1

9
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))              #put array on end of other
print(np.stack((arr1,arr2)))                    #stack arrays, axis defaults to 0
print(np.stack((arr1,arr2), axis = 1))
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [26]:
arr = np.array([1,2,3,4,5,6])
print(np.array_split(arr, 3))
print(np.array_split(arr, 4))

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
